### ISSUE TITLE
As a user I need to be able to create a shopping list for ingrediants

### ISSUE THREAD

**Issue by JeffTanner** [JeffTanner/lunch-lady#2]
Shopping list should include: 
- [ ] Inclusion of all ingredients from planned meals from the calendar
- [ ] Ability to add custom items (not included in the planned meals calendar)
  - Adding custom items should be extremely easy and straightforward, type it and click add
- [ ] Shopping list should display with checkboxes for ease of use when shopping
